import tkinter
from tkinter import *
def add(): result.config(text=(f"{int(num1.get()) + int(num2.get())}"))
def sub(): result.config(text=(f"{int(num1.get()) - int(num2.get())}"))
def mul(): result.config(text=(f"{int(num1.get()) * int(num2.get())}"))
def div(): result.config(text=(f"{int(num1.get()) / int(num2.get())}"))
def floor(): result.config(text=(f"{int(num1.get()) // int(num2.get())}"))
def squ(): result.config(text=(f"{int(num1.get()) ** int(num2.get())}"))
def mod(): result.config(text=(f"{int(num1.get()) % int(num2.get())}"))
win = Tk()
lbl = Label(win, text="CALCULATOR", font=("Segoe Print", 22), bg="#212f3d", fg="white")
lbl.place(x=50, y=10)
lbl1 = Label(win, text="First Number:", font=("Segoe Print", 16), bg="#212f3d", fg="white")
lbl1.place(x=50, y=80)
num1 = Entry(win, font=("Segoe Print", 15))
num1.place(x=240, y=80)
lbl2 = Label(win, text="Second Number:", font=("Segoe Print", 16), bg="#212f3d", fg="white")
lbl2.place(x=50, y=130)
num2 = Entry(win, font=("Segoe Print", 15))
num2.place(x=240, y=130)
lbl3 = Label(win, text="Result:", font=("Segoe Print", 16), bg="#212f3d", fg="white")
lbl3.place(x=50, y=170)
result = Label(win, text=" ", font=("Segoe Print", 16), bg="#212f3d", fg="white")
result.place(x=150, y=170)
add_button = Button(win, width=4, text="+", font=("Gothic Century", 19), command=add, bg="#2c3e50", fg="white")
add_button.place(x=80, y=225)
sub_button = Button(win, width=4, text="-", font=("Gothic Century", 19), command=sub, bg="#2c3e50", fg="white")
sub_button.place(x=150, y=225)
mul_button = Button(win, width=4, text="x", font=("Gothic Century", 19), command=mul, bg="#2c3e50", fg="white")
mul_button.place(x=220, y=225)
div_button = Button(win, width=4, text="/", font=("Gothic Century", 19), command=div, bg="#2c3e50", fg="white")
div_button.place(x=290, y=225)
floor_button = Button(win, width=4, text="//", font=("Gothic Century", 19), command=floor, bg="#2c3e50", fg="white")
floor_button.place(x=360, y=225)
squ_button = Button(win, width=4, text="^", font=("Gothic Century", 19), command=squ, bg="#2c3e50", fg="white")
squ_button.place(x=430, y=225)
mod_button = Button(win, width=4, text="%", font=("Gothic Century", 19), command=mod, bg="#2c3e50", fg="white")
mod_button.place(x=500, y=225)
win.title("Riman's Window")
win.config(bg="#212f3d")
win.geometry("700x350+550+200")
win.mainloop()
